### ISSUE TITLE
Doelgroep is vrij breed

### ISSUE THREAD

**Issue by ghost** [koeenm/fix-the-flow-wireflow#1]
Ik vind dat je de doelgroep in de user story vrij breed heb geschreven. "Bezoeker" kan iedereen zijn die de website van Buurtcampus bezoekt. Is dat ook de doelgroep, of is de doelgroep meer de buurtbewoners van Buurtcampus oost.

**Comment by koeenm** [comment]
met bezoeker bedoel ik de buurtbewoners rond de buurtcampus, die uit willen vinden hoe ze zich bij een initiatief kunnen inschrijven
